export type VocabItem = {
  id: string;
  english: string;
  italian: string;
  pronunciation: string;
  neapolitan?: string;
  note?: string;
};

export type Phrase = {
  id: string;
  situation: string;
  english: string;
  italian: string;
  pronunciation: string;
  neapolitan?: string;
};

export type Category = {
  id: string;
  label: string;
  icon: string;
  vocab: VocabItem[];
  phrases: Phrase[];
};

// Rules enforced: vocab = single words / inseparable fixed terms; phrases =
// multi-word utterances, >=5 per section, matched to the category; universal
// phrases live only in Basics; no phrase duplicates a vocab entry.

export const phraseCategories: Category[] = [
  {
    id: 'basics',
    label: 'Basics',
    icon: 'hand-wave',
    vocab: [
      { id: 'bv1', english: 'Yes', italian: 'Sì', pronunciation: 'see' },
      { id: 'bv2', english: 'No', italian: 'No', pronunciation: 'no' },
      { id: 'bv3', english: 'Please', italian: 'Per favore', pronunciation: 'pehr fah-voh-reh' },
      { id: 'bv4', english: 'Thank you', italian: 'Grazie', pronunciation: 'graht-syeh' },
      { id: 'bv5', english: "You're welcome", italian: 'Prego', pronunciation: 'preh-go' },
      { id: 'bv6', english: 'Hi / Bye (informal)', italian: 'Ciao', pronunciation: 'chow' },
      { id: 'bv7', english: 'Hello (neutral)', italian: 'Salve', pronunciation: 'sahl-veh' },
      { id: 'bv8', english: 'Good morning', italian: 'Buongiorno', pronunciation: 'bwon-johr-no' },
      { id: 'bv9', english: 'Good evening', italian: 'Buonasera', pronunciation: 'bwoh-nah-seh-rah' },
      { id: 'bv10', english: 'Goodbye', italian: 'Arrivederci', pronunciation: 'ah-ree-veh-dehr-chee' },
      { id: 'bv11', english: 'Excuse me (informal)', italian: 'Scusa', pronunciation: 'skoo-zah' },
      { id: 'bv12', english: 'Maybe', italian: 'Forse', pronunciation: 'for-seh' },
      { id: 'bv13', english: 'Today', italian: 'Oggi', pronunciation: 'oh-jee' },
      { id: 'bv14', english: 'Of course', italian: 'Certo', pronunciation: 'chehr-toh' },
    ],
    phrases: [
      { id: 'b1', situation: 'Politeness', english: 'Excuse me (formal)', italian: 'Mi scusi', pronunciation: 'mee skoo-zee' },
      { id: 'b2', situation: 'Requesting', english: 'Can I have...?', italian: 'Posso avere...?', pronunciation: 'poh-so ah-veh-reh' },
      { id: 'b3', situation: 'Requesting', english: 'I would like...', italian: 'Vorrei...', pronunciation: 'voh-ray' },
      { id: 'b4', situation: 'Availability', english: 'Do you have...?', italian: 'Avete...?', pronunciation: 'ah-veh-teh' },
      { id: 'b5', situation: 'Price', english: 'How much does it cost?', italian: 'Quanto costa?', pronunciation: 'kwahn-toh co-stah' },
      { id: 'b6', situation: 'Price', english: 'How much is it all together?', italian: "Quant'è in tutto?", pronunciation: 'kwahn-teh een too-toh' },
      { id: 'b7', situation: 'Paying', english: 'Can I pay by card?', italian: 'Posso pagare con carta?', pronunciation: 'poh-soh pah-gah-reh cohn car-tah' },
      { id: 'b8', situation: 'Recommendation', english: 'What do you recommend?', italian: 'Cosa mi consigli?', pronunciation: 'co-sah mee cohn-see-yee' },
      { id: 'b9', situation: 'Help', english: 'Can you help me?', italian: 'Mi può aiutare?', pronunciation: 'mee pwoh ah-yoo-tah-reh' },
      { id: 'b10', situation: 'Understanding', english: "I don't understand", italian: 'Non capisco', pronunciation: 'non kah-pee-sko' },
      { id: 'b11', situation: 'Language', english: 'Do you speak English?', italian: 'Parla inglese?', pronunciation: 'par-lah een-gleh-zeh' },
      { id: 'b12', situation: 'Browsing', english: "I'm just looking, thanks", italian: 'Sto solo guardando, grazie', pronunciation: 'stoh soh-lo gwar-dahn-doh graht-syeh' },
      { id: 'b13', situation: 'Finishing', english: "That's all, thank you", italian: 'Va bene così, grazie', pronunciation: 'vah beh-neh co-zee graht-syeh' },
    ],
  },
  {
    id: 'pronunciation',
    label: 'Pronunciation',
    icon: 'volume',
    vocab: [
      { id: 'prv1', english: 'Towel', italian: 'Asciugamano', pronunciation: 'ah-shoo-gah-mah-no' },
      { id: 'prv2', english: 'Toasted bread', italian: 'Bruschetta', pronunciation: 'broo-skeh-tah' },
      { id: 'prv3', english: 'Broccoli rabe', italian: 'Friarielli', pronunciation: 'free-ahr-yeh-lee' },
      { id: 'prv4', english: 'Seagull', italian: 'Gabbiano', pronunciation: 'gah-bee-yah-noh' },
      { id: 'prv5', english: 'Shop', italian: 'Negozio', pronunciation: 'neh-goht-syoh' },
      { id: 'prv6', english: 'Rain', italian: 'Pioggia', pronunciation: 'pyoh-jah' },
      { id: 'prv7', english: 'Something', italian: 'Qualcosa', pronunciation: 'kwal-coh-sah' },
      { id: 'prv8', english: 'Scarf', italian: 'Sciarpa', pronunciation: 'shar-pah' },
      { id: 'prv9', english: 'Herbal tea', italian: 'Tisana', pronunciation: 'tee-sah-nah' },
      { id: 'prv10', english: 'Office', italian: 'Ufficio', pronunciation: 'oo-fee-cho' },
      { id: 'prv11', english: 'Cow', italian: 'Vacca', pronunciation: 'vah-cah' },
      { id: 'prv12', english: 'Backpack', italian: 'Zaino', pronunciation: 'zah-yee-noh' },
    ],
    phrases: [
      { id: 'pr1', situation: 'Vowels', english: 'Vowels never change their sound', italian: 'A E I O U', pronunciation: 'ah · eh · ee · oh · oo' },
      { id: 'pr2', situation: 'C & CH', english: 'C is soft before e/i, hard before a/o/u and with h', italian: 'ceci, chiesa, cucina', pronunciation: 'cheh-chee, kyeh-zah, koo-chee-nah' },
      { id: 'pr3', situation: 'G & GH', english: 'G is soft before e/i, hard before a/o/u and with h', italian: 'gelato, spaghetti', pronunciation: 'jeh-lah-toh, spah-geh-tee' },
      { id: 'pr4', situation: 'GLI', english: 'GLI sounds like the "lli" in million', italian: 'figli, famiglia', pronunciation: 'fee-lyee, fah-mee-lyah' },
      { id: 'pr5', situation: 'SC', english: 'SC is "sh" before e/i', italian: 'pesce, sciarpa', pronunciation: 'peh-sheh, shar-pah' },
      { id: 'pr6', situation: 'Stress', english: 'Stress usually falls on the second-to-last syllable', italian: 'amico, ragazzo', pronunciation: 'ah-MEE-co, rah-GAHT-zo' },
    ],
  },
  {
    id: 'numbers',
    label: 'Numbers & time',
    icon: 'clock',
    vocab: [
      { id: 'nv1', english: 'One', italian: 'Uno', pronunciation: 'oo-no' },
      { id: 'nv2', english: 'Two', italian: 'Due', pronunciation: 'doo-eh' },
      { id: 'nv3', english: 'Three', italian: 'Tre', pronunciation: 'treh' },
      { id: 'nv4', english: 'Five', italian: 'Cinque', pronunciation: 'cheen-kweh' },
      { id: 'nv5', english: 'Ten', italian: 'Dieci', pronunciation: 'dyeh-chee' },
      { id: 'nv6', english: 'Twenty', italian: 'Venti', pronunciation: 'ven-tee' },
      { id: 'nv7', english: 'One hundred', italian: 'Cento', pronunciation: 'chen-to' },
      { id: 'nv8', english: 'Today', italian: 'Oggi', pronunciation: 'oh-jee' },
      { id: 'nv9', english: 'Tomorrow', italian: 'Domani', pronunciation: 'doh-mah-nee' },
      { id: 'nv10', english: 'Yesterday', italian: 'Ieri', pronunciation: 'yeh-ree' },
      { id: 'nv11', english: 'Hour', italian: 'Ora', pronunciation: 'oh-rah' },
      { id: 'nv12', english: 'Minute', italian: 'Minuto', pronunciation: 'mee-noo-toh' },
      { id: 'nv13', english: 'Noon', italian: 'Mezzogiorno', pronunciation: 'met-so-johr-no' },
      { id: 'nv14', english: 'Midnight', italian: 'Mezzanotte', pronunciation: 'met-sah-noh-teh' },
    ],
    phrases: [
      { id: 'n1', situation: 'Telling time', english: 'What time is it?', italian: 'Che ore sono?', pronunciation: 'keh oh-reh soh-no' },
      { id: 'n2', situation: 'Telling time', english: "It's four o'clock", italian: 'Sono le quattro', pronunciation: 'soh-no leh kwah-troh' },
      { id: 'n3', situation: 'Telling time', english: "It's half past one", italian: "È l'una e mezza", pronunciation: 'eh loo-nah eh met-sah' },
      { id: 'n4', situation: 'Telling time', english: "It's quarter past three", italian: 'Sono le tre e un quarto', pronunciation: 'soh-no leh treh eh oon kwar-toh' },
      { id: 'n5', situation: 'Planning', english: 'What time shall we meet?', italian: 'A che ora ci vediamo?', pronunciation: 'ah keh oh-rah chee veh-dyah-mo' },
      { id: 'n6', situation: 'Planning', english: 'See you at eight', italian: 'Ci vediamo alle otto', pronunciation: 'chee veh-dyah-mo ah-leh oh-toh' },
      { id: 'n7', situation: 'Duration', english: 'How long does it take?', italian: 'Quanto tempo ci vuole?', pronunciation: 'kwahn-to tem-po chee vwoh-leh' },
    ],
  },
  {
    id: 'groceries',
    label: 'Groceries',
    icon: 'shopping-bag',
    vocab: [
      { id: 'gv1', english: 'Meat', italian: 'Carne', pronunciation: 'car-neh' },
      { id: 'gv2', english: 'Chicken', italian: 'Pollo', pronunciation: 'poh-loh' },
      { id: 'gv3', english: 'Cheese', italian: 'Formaggio', pronunciation: 'for-mah-joh' },
      { id: 'gv4', english: 'Cold cuts', italian: 'Salumi', pronunciation: 'sah-loo-mee' },
      { id: 'gv5', english: 'Milk', italian: 'Latte', pronunciation: 'lah-teh' },
      { id: 'gv6', english: 'Butter', italian: 'Burro', pronunciation: 'boo-roh' },
      { id: 'gv7', english: 'Eggs', italian: 'Uova', pronunciation: 'woh-va' },
      { id: 'gv8', english: 'Salt', italian: 'Sale', pronunciation: 'sah-leh' },
      { id: 'gv9', english: 'Pepper', italian: 'Pepe', pronunciation: 'peh-peh' },
      { id: 'gv10', english: 'Sugar', italian: 'Zucchero', pronunciation: 'tsoo-keh-roh' },
      { id: 'gv11', english: 'Bread', italian: 'Pane', pronunciation: 'pah-neh' },
      { id: 'gv12', english: 'Oil', italian: 'Olio', pronunciation: 'oh-lee-oh' },
      { id: 'gv13', english: 'Vinegar', italian: 'Aceto', pronunciation: 'ah-cheh-toh' },
      { id: 'gv14', english: 'Frozen', italian: 'Congelato', pronunciation: 'cohn-jeh-lah-toh' },
      { id: 'gv15', english: 'Fresh', italian: 'Fresco', pronunciation: 'freh-scoh' },
      { id: 'gv16', english: 'Shopping cart', italian: 'Carrello', pronunciation: 'car-reh-loh' },
      { id: 'gv17', english: 'Bag', italian: 'Busta', pronunciation: 'boo-stah' },
    ],
    phrases: [
      { id: 'g1', situation: 'Finding items', english: 'Where is the frozen section?', italian: 'Dov’è il reparto dei surgelati?', pronunciation: 'doh-veh eel reh-par-toh day soor-jeh-lah-tee' },
      { id: 'g2', situation: 'Finding items', english: 'Where are the eggs?', italian: 'Dove sono le uova?', pronunciation: 'doh-veh soh-no leh woh-va' },
      { id: 'g3', situation: 'Quality', english: 'Is this bread fresh today?', italian: 'Questo pane è fresco di oggi?', pronunciation: 'kweh-stoh pah-neh eh freh-scoh dee oh-jee' },
      { id: 'g4', situation: 'Quantity', english: 'Can you give me half a kilo of cheese?', italian: 'Mi dà mezzo chilo di formaggio?', pronunciation: 'mee dah met-so kee-loh dee for-mah-joh' },
      { id: 'g5', situation: 'Dietary', english: 'Is there lactose-free milk?', italian: "C'è il latte senza lattosio?", pronunciation: 'cheh eel lah-teh sen-tsah lah-toh-syoh' },
      { id: 'g6', situation: 'Checkout', english: 'Do I leave the cart here?', italian: 'Lascio il carrello qui?', pronunciation: 'lah-shoh eel car-reh-loh kwee' },
    ],
  },
  {
    id: 'butcher',
    label: 'Butcher & fish',
    icon: 'meat',
    vocab: [
      { id: 'btv1', english: 'Butcher', italian: 'Macellaio', pronunciation: 'mah-cheh-lah-yoh' },
      { id: 'btv2', english: 'Fishmonger', italian: 'Pescivendolo', pronunciation: 'peh-shee-ven-doh-loh' },
      { id: 'btv3', english: 'Steak', italian: 'Bistecca', pronunciation: 'bee-stek-ah' },
      { id: 'btv4', english: 'Beef', italian: 'Manzo', pronunciation: 'mahn-tsoh' },
      { id: 'btv5', english: 'Lamb', italian: 'Agnello', pronunciation: 'ahn-yel-lo' },
      { id: 'btv6', english: 'Turkey', italian: 'Tacchino', pronunciation: 'tah-kee-noh' },
      { id: 'btv7', english: 'Sausage', italian: 'Salsiccia', pronunciation: 'sahl-see-cha' },
      { id: 'btv8', english: 'Ground (minced)', italian: 'Macinato', pronunciation: 'mah-chee-nah-toh' },
      { id: 'btv9', english: 'Tuna', italian: 'Tonno', pronunciation: 'tohn-noh' },
      { id: 'btv10', english: 'Sea bass', italian: 'Spigola', pronunciation: 'spee-go-lah' },
      { id: 'btv11', english: 'Salmon', italian: 'Salmone', pronunciation: 'sahl-moh-neh' },
      { id: 'btv12', english: 'Clams', italian: 'Vongole', pronunciation: 'vohn-goh-leh' },
      { id: 'btv13', english: 'Mussels', italian: 'Cozze', pronunciation: 'coh-tseh' },
      { id: 'btv14', english: 'Shrimp', italian: 'Gamberi', pronunciation: 'gahm-beh-ree' },
      { id: 'btv15', english: 'Anchovies', italian: 'Alici', pronunciation: 'ah-lee-chee' },
    ],
    phrases: [
      { id: 'bt1', situation: 'Preparation', english: 'Can you cut the chicken into thin slices?', italian: 'Puoi tagliare il pollo a fette sottili?', pronunciation: 'pwoy tah-ya-reh eel poh-loh ah feh-teh so-tee-lee' },
      { id: 'bt2', situation: 'Preparation', english: 'Can you grind this beef?', italian: 'Puoi macinare questo manzo?', pronunciation: 'pwoy mah-chee-nah-reh kweh-stoh mahn-tsoh' },
      { id: 'bt3', situation: 'Preparation', english: 'Can you filet the fish?', italian: 'Puoi sfilettare il pesce?', pronunciation: 'pwoy sfee-leh-tah-reh eel peh-sheh' },
      { id: 'bt4', situation: 'Quality', english: 'Is the fish fresh today?', italian: 'Il pesce è fresco di oggi?', pronunciation: 'eel peh-sheh eh freh-scoh dee oh-jee' },
      { id: 'bt5', situation: 'Quantity', english: "I'd like two slices of ham", italian: 'Vorrei due fette di prosciutto', pronunciation: 'voh-ray doo-eh feh-teh dee pro-shoo-toh' },
      { id: 'bt6', situation: 'Weight', english: 'How much does this steak weigh?', italian: 'Quanto pesa questa bistecca?', pronunciation: 'kwahn-to peh-sah kweh-stah bee-stek-ah' },
    ],
  },
  {
    id: 'produce',
    label: 'Food market',
    icon: 'apple',
    vocab: [
      { id: 'pdv1', english: 'Fruit', italian: 'Frutta', pronunciation: 'froo-tah' },
      { id: 'pdv2', english: 'Vegetables', italian: 'Verdura', pronunciation: 'vehr-doo-rah' },
      { id: 'pdv3', english: 'Citrus fruit', italian: 'Agrumi', pronunciation: 'ah-groo-mee' },
      { id: 'pdv4', english: 'Salad greens', italian: 'Insalata', pronunciation: 'een-sah-lah-tah' },
      { id: 'pdv5', english: 'Herbs', italian: 'Erbe', pronunciation: 'ehr-beh' },
      { id: 'pdv6', english: 'Spices', italian: 'Spezie', pronunciation: 'spet-see-eh' },
      { id: 'pdv7', english: 'Onion', italian: 'Cipolla', pronunciation: 'chee-poh-lah' },
      { id: 'pdv8', english: 'Lemon', italian: 'Limone', pronunciation: 'lee-moh-neh' },
      { id: 'pdv9', english: 'Orange', italian: 'Arancia', pronunciation: 'ah-rahn-cha' },
      { id: 'pdv10', english: 'Tomatoes', italian: 'Pomodori', pronunciation: 'po-mo-doh-ree' },
      { id: 'pdv11', english: 'Basil', italian: 'Basilico', pronunciation: 'bah-zee-lee-co' },
      { id: 'pdv12', english: 'Seasonal', italian: 'Stagionale', pronunciation: 'stah-joh-nah-leh' },
      { id: 'pdv13', english: 'Ripe', italian: 'Maturo', pronunciation: 'mah-too-roh' },
    ],
    phrases: [
      { id: 'pd1', situation: 'Seasonality', english: 'Are the strawberries in season?', italian: 'Sono di stagione le fragole?', pronunciation: 'soh-no dee stah-joh-neh leh frah-go-leh' },
      { id: 'pd2', situation: 'Quantity', english: "I'd like a bunch of basil", italian: 'Vorrei un mazzo di basilico', pronunciation: 'voh-ray oon mah-tso dee bah-zee-lee-co' },
      { id: 'pd3', situation: 'Quality', english: 'Are these tomatoes ripe?', italian: 'Questi pomodori sono maturi?', pronunciation: 'kweh-stee po-mo-doh-ree soh-no mah-too-ree' },
      { id: 'pd4', situation: 'Quantity', english: 'Give me a kilo of them', italian: 'Me ne dia un chilo', pronunciation: 'meh neh dee-ah oon kee-loh' },
      { id: 'pd5', situation: 'Origin', english: 'Are they grown locally?', italian: 'Sono coltivati qui?', pronunciation: 'soh-no col-tee-vah-tee kwee' },
      { id: 'pd6', situation: 'Price', english: 'How much are the oranges?', italian: 'Quanto vengono le arance?', pronunciation: 'kwahn-to ven-go-no leh ah-rahn-cheh' },
    ],
  },
  {
    id: 'shopping',
    label: 'Shopping & money',
    icon: 'shopping-cart',
    vocab: [
      { id: 'shv1', english: 'Hectogram (100g)', italian: 'Etto', pronunciation: 'eh-toh', note: 'plural: etti' },
      { id: 'shv2', english: 'Kilo', italian: 'Chilo', pronunciation: 'kee-loh' },
      { id: 'shv3', english: 'Litre', italian: 'Litro', pronunciation: 'leet-roh' },
      { id: 'shv4', english: 'Weight', italian: 'Peso', pronunciation: 'peh-so' },
      { id: 'shv5', english: 'Cash', italian: 'Contanti', pronunciation: 'cohn-tahn-tee' },
      { id: 'shv6', english: 'Change (money back)', italian: 'Resto', pronunciation: 'reh-stoh' },
      { id: 'shv7', english: 'Receipt', italian: 'Scontrino', pronunciation: 'skon-tree-no' },
      { id: 'shv8', english: 'Discount', italian: 'Sconto', pronunciation: 'skon-toh' },
      { id: 'shv9', english: 'Sales', italian: 'Saldi', pronunciation: 'sahl-dee' },
      { id: 'shv10', english: 'Price', italian: 'Prezzo', pronunciation: 'pret-so' },
      { id: 'shv11', english: 'Expensive', italian: 'Caro', pronunciation: 'kah-roh' },
      { id: 'shv12', english: 'Cheap', italian: 'Economico', pronunciation: 'eh-co-noh-mee-co' },
      { id: 'shv13', english: 'ATM', italian: 'Bancomat', pronunciation: 'bahn-co-maht' },
    ],
    phrases: [
      { id: 'sh1', situation: 'Payment', english: 'Can I pay in cash?', italian: 'Posso pagare in contanti?', pronunciation: 'poh-so pah-gah-reh een cohn-tahn-tee' },
      { id: 'sh2', situation: 'Payment', english: 'Do you accept credit cards?', italian: 'Accettate carte di credito?', pronunciation: 'ah-cheh-tah-teh car-teh dee creh-dee-toh' },
      { id: 'sh3', situation: 'Bargaining', english: 'Is there a discount?', italian: "C'è uno sconto?", pronunciation: 'cheh oo-no skon-toh' },
      { id: 'sh4', situation: 'Bargaining', english: 'Can you give me a better price?', italian: 'Mi può fare un prezzo?', pronunciation: 'mee pwoh fah-reh oon pret-so' },
      { id: 'sh5', situation: 'Bargaining', english: "It's too expensive", italian: 'È troppo caro', pronunciation: 'eh trop-po kah-roh' },
      { id: 'sh6', situation: 'Receipt', english: 'Can I have the receipt?', italian: 'Mi dà lo scontrino?', pronunciation: 'mee dah lo skon-tree-no' },
    ],
  },
  {
    id: 'pastry',
    label: 'Pastry shop',
    icon: 'cake',
    vocab: [
      { id: 'pav1', english: 'Pastry shop', italian: 'Pasticceria', pronunciation: 'pah-stee-cheh-ree-yah' },
      { id: 'pav2', english: 'Chocolate', italian: 'Cioccolato', pronunciation: 'choh-coh-lah-toh' },
      { id: 'pav3', english: 'Black cherry', italian: 'Amarena', pronunciation: 'ah-mah-reh-nah' },
      { id: 'pav4', english: 'Pistachio', italian: 'Pistacchio', pronunciation: 'pee-stah-kyo' },
      { id: 'pav5', english: 'Hazelnut', italian: 'Nocciola', pronunciation: 'no-choh-lah' },
      { id: 'pav6', english: 'Custard', italian: 'Crema', pronunciation: 'creh-mah' },
      { id: 'pav7', english: 'Sweetened ricotta', italian: 'Ricotta', pronunciation: 'ree-coh-tah' },
      { id: 'pav8', english: 'Honey', italian: 'Miele', pronunciation: 'myeh-leh' },
      { id: 'pav9', english: 'Sfogliatella (pastry)', italian: 'Sfogliatella', pronunciation: 'sfoh-lyah-teh-lah' },
      { id: 'pav10', english: 'Rum cake', italian: 'Babà', pronunciation: 'bah-bah' },
      { id: 'pav11', english: 'Croissant', italian: 'Cornetto', pronunciation: 'cor-neh-toh' },
    ],
    phrases: [
      { id: 'pa1', situation: 'Ordering', english: "I'd like a warm sfogliatella", italian: 'Vorrei una sfogliatella calda', pronunciation: 'voh-ray oo-nah sfoh-lyah-teh-lah cahl-dah' },
      { id: 'pa2', situation: 'Quality', english: 'Are the pastries fresh?', italian: 'Sono fresche le paste?', pronunciation: 'soh-no freh-skeh leh pah-steh' },
      { id: 'pa3', situation: 'Ordering', english: 'Give me six, assorted', italian: 'Me ne dia sei, assortite', pronunciation: 'meh neh dee-ah say ah-sor-tee-teh' },
      { id: 'pa4', situation: 'Local specialties', english: 'Do you have typical Neapolitan sweets?', italian: 'Avete dolci tipici napoletani?', pronunciation: 'ah-veh-teh dol-chee tee-pee-chee nah-po-leh-tah-nee' },
      { id: 'pa5', situation: 'Price', english: 'How much is each one?', italian: 'Quanto costa al pezzo?', pronunciation: 'kwahn-to co-stah ahl pet-so' },
      { id: 'pa6', situation: 'Dietary', english: 'Is there anything without cream?', italian: "C'è qualcosa senza crema?", pronunciation: 'cheh kwal-coh-sah sen-tsah creh-mah' },
    ],
  },
  {
    id: 'wine',
    label: 'Wine shop',
    icon: 'glass',
    vocab: [
      { id: 'wv1', english: 'Wine shop', italian: 'Enoteca', pronunciation: 'eh-no-teh-kah' },
      { id: 'wv2', english: 'Wine', italian: 'Vino', pronunciation: 'vee-no' },
      { id: 'wv3', english: 'Red', italian: 'Rosso', pronunciation: 'roh-soh' },
      { id: 'wv4', english: 'White', italian: 'Bianco', pronunciation: 'byahn-koh' },
      { id: 'wv5', english: 'Sparkling wine', italian: 'Spumante', pronunciation: 'spoo-mahn-teh' },
      { id: 'wv6', english: 'Dry', italian: 'Secco', pronunciation: 'seh-koh' },
      { id: 'wv7', english: 'Full-bodied', italian: 'Corposo', pronunciation: 'cohr-poh-soh' },
      { id: 'wv8', english: 'Fruity', italian: 'Fruttato', pronunciation: 'froo-tah-toh' },
      { id: 'wv9', english: 'Aged', italian: 'Invecchiato', pronunciation: 'een-veh-kyah-toh' },
      { id: 'wv10', english: 'Wine glass', italian: 'Calice', pronunciation: 'kah-lee-cheh' },
      { id: 'wv11', english: 'Bottle', italian: 'Bottiglia', pronunciation: 'boh-tee-ya' },
    ],
    phrases: [
      { id: 'w1', situation: 'Recommendation', english: 'Can you recommend a full-bodied red?', italian: 'Mi consiglia un rosso corposo?', pronunciation: 'mee cohn-see-yah oon roh-soh cohr-poh-soh' },
      { id: 'w2', situation: 'Local wine', english: "I'd like a wine from Campania", italian: 'Vorrei un vino della Campania', pronunciation: 'voh-ray oon vee-no deh-lah cahm-pah-nyah' },
      { id: 'w3', situation: 'Pairing', english: 'Which wine pairs with fish?', italian: 'Che vino si abbina al pesce?', pronunciation: 'keh vee-no see ah-bee-nah ahl peh-sheh' },
      { id: 'w4', situation: 'Tasting', english: 'Can I taste it?', italian: 'Posso assaggiarlo?', pronunciation: 'poh-so ah-sah-jar-lo' },
      { id: 'w5', situation: 'Style', english: 'Is it a dry or sweet wine?', italian: 'È un vino secco o dolce?', pronunciation: 'eh oon vee-no seh-koh o dol-cheh' },
      { id: 'w6', situation: 'Price', english: 'How much is this bottle?', italian: 'Quanto costa questa bottiglia?', pronunciation: 'kwahn-to co-stah kweh-stah boh-tee-ya' },
    ],
  },
  {
    id: 'cafe',
    label: 'Café & bar',
    icon: 'coffee',
    vocab: [
      { id: 'cv1', english: 'Espresso', italian: 'Caffè', pronunciation: 'kah-feh', note: '"un caffè" means an espresso by default' },
      { id: 'cv2', english: 'Cappuccino', italian: 'Cappuccino', pronunciation: 'kap-poo-chee-no' },
      { id: 'cv3', english: 'Croissant', italian: 'Cornetto', pronunciation: 'cor-neh-toh' },
      { id: 'cv4', english: 'Decaf', italian: 'Decaffeinato', pronunciation: 'deh-caf-ay-nah-toh' },
      { id: 'cv5', english: 'Tea', italian: 'Tè', pronunciation: 'teh' },
      { id: 'cv6', english: 'Beer', italian: 'Birra', pronunciation: 'bee-rah' },
      { id: 'cv7', english: 'Dark beer', italian: 'Scura', pronunciation: 'scoo-rah' },
      { id: 'cv8', english: 'Ice', italian: 'Ghiaccio', pronunciation: 'gyah-cho' },
      { id: 'cv9', english: 'Digestif', italian: 'Digestivo', pronunciation: 'dee-jeh-stee-voh' },
      { id: 'cv10', english: 'The counter', italian: 'Banco', pronunciation: 'bahn-ko', note: 'standing here is cheaper than a table' },
    ],
    phrases: [
      { id: 'c1', situation: 'Ordering', english: 'An espresso at the counter, please', italian: 'Un caffè al banco, per favore', pronunciation: 'oon kah-feh ahl bahn-ko pehr fah-voh-reh' },
      { id: 'c2', situation: 'Ordering', english: 'A cappuccino and a croissant', italian: 'Un cappuccino e un cornetto', pronunciation: 'oon kap-poo-chee-no eh oon cor-neh-toh' },
      { id: 'c3', situation: 'Ordering', english: "I'd like a macchiato", italian: 'Vorrei un caffè macchiato', pronunciation: 'voh-ray oon kah-feh mah-kyah-toh' },
      { id: 'c4', situation: 'Naples tradition', english: 'A "suspended" coffee (paid forward)', italian: 'Un caffè sospeso', pronunciation: 'oon kah-feh sos-peh-zo' },
      { id: 'c5', situation: 'Water', english: 'A glass of water, please', italian: "Un bicchiere d'acqua, per favore", pronunciation: 'oon bee-kyeh-reh dah-kwah pehr fah-voh-reh' },
      { id: 'c6', situation: 'Paying', english: 'Do I pay at the counter or the table?', italian: 'Pago al banco o al tavolo?', pronunciation: 'pah-go ahl bahn-ko o ahl tah-vo-lo' },
    ],
  },
  {
    id: 'restaurant',
    label: 'Restaurant',
    icon: 'utensils',
    vocab: [
      { id: 'rv1', english: 'Restaurant', italian: 'Ristorante', pronunciation: 'ree-stoh-rahn-teh' },
      { id: 'rv2', english: 'Local-food restaurant', italian: 'Trattoria', pronunciation: 'trah-toh-ree-yah' },
      { id: 'rv3', english: 'Starter', italian: 'Antipasto', pronunciation: 'an-tee-pas-toh' },
      { id: 'rv4', english: 'First course', italian: 'Primo', pronunciation: 'pree-mo' },
      { id: 'rv5', english: 'Second course', italian: 'Secondo', pronunciation: 'seh-kon-do' },
      { id: 'rv6', english: 'Side dish', italian: 'Contorno', pronunciation: 'con-tor-no' },
      { id: 'rv7', english: 'Dessert', italian: 'Dolce', pronunciation: 'dol-cheh' },
      { id: 'rv8', english: 'Menu', italian: 'Menù', pronunciation: 'meh-noo' },
      { id: 'rv9', english: 'Waiter', italian: 'Cameriere', pronunciation: 'kah-meh-ryeh-reh' },
      { id: 'rv10', english: 'Cover charge', italian: 'Coperto', pronunciation: 'co-pehr-toh' },
      { id: 'rv11', english: 'The bill', italian: 'Conto', pronunciation: 'con-toh' },
    ],
    phrases: [
      { id: 'r1', situation: 'Arriving', english: 'A table for two, please', italian: 'Un tavolo per due, per favore', pronunciation: 'oon tah-vo-lo pehr doo-eh pehr fah-voh-reh' },
      { id: 'r2', situation: 'Reservation', english: "I'd like to book for tonight", italian: 'Vorrei prenotare per stasera', pronunciation: 'voh-ray preh-no-tah-reh pehr stah-seh-rah' },
      { id: 'r3', situation: 'Ordering', english: "What's the dish of the day?", italian: 'Qual è il piatto del giorno?', pronunciation: 'kwah-leh eel pyah-toh del johr-no' },
      { id: 'r4', situation: 'Dietary', english: "I'm allergic to seafood", italian: 'Sono allergico ai frutti di mare', pronunciation: 'soh-no ah-ler-jee-co eye froo-tee dee mah-reh' },
      { id: 'r5', situation: 'Drinks', english: 'Still or sparkling water?', italian: 'Acqua naturale o frizzante?', pronunciation: 'ah-kwah nah-too-rah-leh o free-tsahn-teh' },
      { id: 'r6', situation: 'Paying', english: 'The bill, please', italian: 'Il conto, per favore', pronunciation: 'eel con-toh pehr fah-voh-reh' },
      { id: 'r7', situation: 'Compliment', english: 'It was all delicious', italian: 'Era tutto buonissimo', pronunciation: 'eh-rah too-toh bwoh-nee-see-mo' },
    ],
  },
  {
    id: 'hardware',
    label: 'Hardware store',
    icon: 'tool',
    vocab: [
      { id: 'hwv1', english: 'Hardware store', italian: 'Ferramenta', pronunciation: 'feh-rah-men-tah' },
      { id: 'hwv2', english: 'Tools', italian: 'Attrezzi', pronunciation: 'ah-tret-see' },
      { id: 'hwv3', english: 'Hammer', italian: 'Martello', pronunciation: 'mar-tel-loh' },
      { id: 'hwv4', english: 'Screwdriver', italian: 'Cacciavite', pronunciation: 'cah-cha-vee-teh' },
      { id: 'hwv5', english: 'Screw', italian: 'Vite', pronunciation: 'vee-teh' },
      { id: 'hwv6', english: 'Nail', italian: 'Chiodo', pronunciation: 'kyoh-doh' },
      { id: 'hwv7', english: 'Drill', italian: 'Trapano', pronunciation: 'trah-pah-no' },
      { id: 'hwv8', english: 'Key', italian: 'Chiave', pronunciation: 'kyah-veh' },
      { id: 'hwv9', english: 'Paint', italian: 'Pittura', pronunciation: 'peet-too-rah' },
      { id: 'hwv10', english: 'Glue', italian: 'Colla', pronunciation: 'col-lah' },
      { id: 'hwv11', english: 'Lightbulb', italian: 'Lampadina', pronunciation: 'lahm-pah-dee-nah' },
    ],
    phrases: [
      { id: 'hw1', situation: 'Asking', english: 'I need something to hang a picture', italian: 'Mi serve qualcosa per appendere un quadro', pronunciation: 'mee sehr-veh kwal-coh-sah pehr ah-pen-deh-reh oon kwah-droh' },
      { id: 'hw2', situation: 'Finding items', english: "I'm looking for longer screws", italian: 'Cerco delle viti più lunghe', pronunciation: 'chehr-co deh-leh vee-tee pyoo loon-geh' },
      { id: 'hw3', situation: 'Service', english: 'Can you make a copy of this key?', italian: 'Si può fare una copia di questa chiave?', pronunciation: 'see pwoh fah-reh oo-nah co-pyah dee kweh-stah kyah-veh' },
      { id: 'hw4', situation: 'Advice', english: 'Which glue works for wood?', italian: 'Che colla va bene per il legno?', pronunciation: 'keh col-lah vah beh-neh pehr eel leh-nyo' },
      { id: 'hw5', situation: 'Finding items', english: 'Do you have LED bulbs?', italian: 'Avete lampadine a LED?', pronunciation: 'ah-veh-teh lahm-pah-dee-neh ah led' },
      { id: 'hw6', situation: 'Tools', english: 'Do you have a wrench?', italian: 'Avete una chiave inglese?', pronunciation: 'ah-veh-teh oo-nah kyah-veh een-gleh-zeh' },
    ],
  },
  {
    id: 'kitchen',
    label: 'Kitchen & home',
    icon: 'home',
    vocab: [
      { id: 'kv1', english: 'Pot', italian: 'Pentola', pronunciation: 'pen-toh-lah' },
      { id: 'kv2', english: 'Frying pan', italian: 'Padella', pronunciation: 'pah-del-lah' },
      { id: 'kv3', english: 'Glass', italian: 'Bicchiere', pronunciation: 'bee-kyeh-reh' },
      { id: 'kv4', english: 'Spoon', italian: 'Cucchiaio', pronunciation: 'koo-kyah-yo' },
      { id: 'kv5', english: 'Fork', italian: 'Forchetta', pronunciation: 'for-keh-tah' },
      { id: 'kv6', english: 'Knife', italian: 'Coltello', pronunciation: 'cohl-tel-loh' },
      { id: 'kv7', english: 'Plate', italian: 'Piatto', pronunciation: 'pyah-toh' },
      { id: 'kv8', english: 'Bowl', italian: 'Ciotola', pronunciation: 'cho-toh-lah' },
      { id: 'kv9', english: 'Cutting board', italian: 'Tagliere', pronunciation: 'tah-yeh-reh' },
      { id: 'kv10', english: 'Tablecloth', italian: 'Tovaglia', pronunciation: 'toh-vah-yah' },
      { id: 'kv11', english: 'Napkin', italian: 'Tovagliolo', pronunciation: 'toh-vah-yoh-loh' },
      { id: 'kv12', english: 'Coffee cup', italian: 'Tazza', pronunciation: 'tah-tsah' },
    ],
    phrases: [
      { id: 'k1', situation: 'Finding items', english: 'Where are the plates?', italian: 'Dove sono i piatti?', pronunciation: 'doh-veh soh-no ee pyah-tee' },
      { id: 'k2', situation: 'Cookware', english: 'I need a non-stick pan', italian: 'Mi serve una padella antiaderente', pronunciation: 'mee sehr-veh oo-nah pah-del-lah an-tee-ah-deh-ren-teh' },
      { id: 'k3', situation: 'Glassware', english: 'Do you have wine glasses?', italian: 'Avete bicchieri da vino?', pronunciation: 'ah-veh-teh bee-kyeh-ree dah vee-no' },
      { id: 'k4', situation: 'Care', english: 'Is this dishwasher-safe?', italian: 'Questo è lavabile in lavastoviglie?', pronunciation: 'kweh-stoh eh lah-vah-bee-leh een lah-vah-stoh-vee-yeh' },
      { id: 'k5', situation: 'Shopping', english: "I'm looking for a cutlery set", italian: 'Cerco un set di posate', pronunciation: 'chehr-co oon set dee po-sah-teh' },
      { id: 'k6', situation: 'Sizing', english: 'Do you have bigger tablecloths?', italian: 'Avete tovaglie più grandi?', pronunciation: 'ah-veh-teh toh-vah-yeh pyoo grahn-dee' },
    ],
  },
  {
    id: 'cleaning',
    label: 'Cleaning & laundry',
    icon: 'spray',
    vocab: [
      { id: 'clv1', english: 'Broom', italian: 'Scopa', pronunciation: 'scoh-pah' },
      { id: 'clv2', english: 'Dustpan', italian: 'Paletta', pronunciation: 'pah-let-tah' },
      { id: 'clv3', english: 'Mop', italian: 'Mocio', pronunciation: 'moh-cho' },
      { id: 'clv4', english: 'Bucket', italian: 'Secchio', pronunciation: 'seh-kyoh' },
      { id: 'clv5', english: 'Sponge', italian: 'Spugna', pronunciation: 'spoon-yah' },
      { id: 'clv6', english: 'Bleach', italian: 'Candeggina', pronunciation: 'cahn-deh-jee-nah' },
      { id: 'clv7', english: 'Fabric softener', italian: 'Ammorbidente', pronunciation: 'ah-mohr-bee-den-teh' },
      { id: 'clv8', english: 'Degreaser', italian: 'Sgrassatore', pronunciation: 'sgrah-sah-toh-reh' },
      { id: 'clv9', english: 'Vacuum cleaner', italian: 'Aspirapolvere', pronunciation: 'ah-spee-rah-pohl-veh-reh' },
      { id: 'clv10', english: 'Stain', italian: 'Macchia', pronunciation: 'mah-kyah' },
    ],
    phrases: [
      { id: 'cl1', situation: 'Finding items', english: "Where's the dish soap?", italian: 'Dove si trova il detersivo per i piatti?', pronunciation: 'doh-veh see troh-vah eel deh-tehr-see-voh pehr ee pyah-tee' },
      { id: 'cl2', situation: 'Advice', english: 'Do you have a good degreaser?', italian: 'Avete un buon sgrassatore?', pronunciation: 'ah-veh-teh oon bwon sgrah-sah-toh-reh' },
      { id: 'cl3', situation: 'Suitability', english: 'Is this suitable for parquet floors?', italian: 'Questo è adatto per il parquet?', pronunciation: 'kweh-stoh eh ah-dah-toh pehr eel par-keh' },
      { id: 'cl4', situation: 'Laundry', english: "I'd like to take this to the laundry", italian: 'Vorrei portare questo in lavanderia', pronunciation: 'voh-ray por-tah-reh kweh-stoh een lah-vahn-deh-ree-ah' },
      { id: 'cl5', situation: 'Laundry', english: 'How much is dry cleaning?', italian: 'Quanto costa il lavaggio a secco?', pronunciation: 'kwahn-to co-stah eel lah-vah-joh ah seh-koh' },
      { id: 'cl6', situation: 'Stains', english: "I'm looking for something for stains", italian: 'Cerco qualcosa per le macchie', pronunciation: 'chehr-co kwal-coh-sah pehr leh mah-kyeh' },
    ],
  },
  {
    id: 'car',
    label: 'Car & mechanic',
    icon: 'car',
    vocab: [
      { id: 'crv1', english: 'Engine', italian: 'Motore', pronunciation: 'moh-toh-reh' },
      { id: 'crv2', english: 'Motor oil', italian: 'Olio', pronunciation: 'oh-lee-oh' },
      { id: 'crv3', english: 'Windshield', italian: 'Parabrezza', pronunciation: 'pah-rah-bret-sah' },
      { id: 'crv4', english: 'Gasoline', italian: 'Benzina', pronunciation: 'ben-tsee-nah' },
      { id: 'crv5', english: 'Brakes', italian: 'Freni', pronunciation: 'freh-nee' },
      { id: 'crv6', english: 'Clutch', italian: 'Frizione', pronunciation: 'freet-syoh-neh' },
      { id: 'crv7', english: 'Battery', italian: 'Batteria', pronunciation: 'bah-teh-ree-yah' },
      { id: 'crv8', english: 'Tires', italian: 'Gomme', pronunciation: 'goh-meh' },
      { id: 'crv9', english: 'Mechanic', italian: 'Meccanico', pronunciation: 'meh-cahn-nee-coh' },
      { id: 'crv10', english: 'Repair shop', italian: 'Officina', pronunciation: 'oh-fee-chee-nah' },
      { id: 'crv11', english: 'Full (tank)', italian: 'Pieno', pronunciation: 'pyen-oh' },
    ],
    phrases: [
      { id: 'cr1', situation: 'Service', english: "I'd like an oil change", italian: "Vorrei fare un cambio dell'olio", pronunciation: 'voh-ray fah-reh oon cahm-byoh del-oh-lee-oh' },
      { id: 'cr2', situation: 'Problem', english: 'I have a flat tire', italian: 'Ho una gomma a terra', pronunciation: 'oh oo-nah goh-mah ah teh-rah' },
      { id: 'cr3', situation: 'Problem', english: 'The engine makes a strange noise', italian: 'Il motore fa un rumore strano', pronunciation: 'eel moh-toh-reh fah oon roo-moh-reh strah-no' },
      { id: 'cr4', situation: 'Service', english: 'Can you check the brakes?', italian: 'Può controllare i freni?', pronunciation: 'pwoh con-trol-lah-reh ee freh-nee' },
      { id: 'cr5', situation: 'Gas station', english: 'Fill it up, please', italian: 'Il pieno, per favore', pronunciation: 'eel pyen-oh pehr fah-voh-reh' },
      { id: 'cr6', situation: 'Timing', english: 'How long will the repair take?', italian: 'Quanto ci vuole per ripararla?', pronunciation: 'kwahn-to chee vwoh-leh pehr ree-pah-rar-lah' },
    ],
  },
  {
    id: 'pharmacy',
    label: 'Pharmacy',
    icon: 'first-aid',
    vocab: [
      { id: 'pv1', english: 'Pharmacy', italian: 'Farmacia', pronunciation: 'far-mah-chee-yah' },
      { id: 'pv2', english: 'Medicine', italian: 'Medicina', pronunciation: 'meh-dee-chee-nah' },
      { id: 'pv3', english: 'Prescription', italian: 'Ricetta', pronunciation: 'ree-cheh-tah' },
      { id: 'pv4', english: 'Painkiller', italian: 'Antidolorifico', pronunciation: 'an-tee-do-lo-ree-fee-co' },
      { id: 'pv5', english: 'Pain', italian: 'Dolore', pronunciation: 'do-loh-reh' },
      { id: 'pv6', english: 'Fever', italian: 'Febbre', pronunciation: 'feh-breh' },
      { id: 'pv7', english: 'Cough', italian: 'Tosse', pronunciation: 'toh-seh' },
      { id: 'pv8', english: 'Cold (illness)', italian: 'Raffreddore', pronunciation: 'rahf-freh-doh-reh' },
      { id: 'pv9', english: 'Allergy', italian: 'Allergia', pronunciation: 'ah-lehr-jee-ah' },
      { id: 'pv10', english: 'Band-aid', italian: 'Cerotto', pronunciation: 'cheh-roh-toh' },
      { id: 'pv11', english: 'Dentist', italian: 'Dentista', pronunciation: 'dehn-tee-stah' },
    ],
    phrases: [
      { id: 'ph1', situation: 'Symptoms', english: 'I need something for a headache', italian: 'Ho bisogno di qualcosa per il mal di testa', pronunciation: 'oh bee-zon-yo dee kwal-coh-sah pehr eel mal dee teh-stah' },
      { id: 'ph2', situation: 'Symptoms', english: 'I have a sore throat and a cough', italian: 'Ho mal di gola e tosse', pronunciation: 'oh mal dee goh-lah eh toh-seh' },
      { id: 'ph3', situation: 'Prescription', english: 'Do I need a prescription?', italian: 'Mi serve la ricetta?', pronunciation: 'mee sehr-veh lah ree-cheh-tah' },
      { id: 'ph4', situation: 'Allergy', english: "I'm allergic to penicillin", italian: 'Sono allergico alla penicillina', pronunciation: 'soh-no ah-ler-jee-co ah-lah peh-nee-chee-lee-nah' },
      { id: 'ph5', situation: 'Requesting', english: 'Do you have a painkiller?', italian: 'Avete un antidolorifico?', pronunciation: 'ah-veh-teh oon an-tee-do-lo-ree-fee-co' },
      { id: 'ph6', situation: 'Symptoms', english: 'Do you have something for mosquito bites?', italian: 'Avete qualcosa per le punture di zanzara?', pronunciation: 'ah-veh-teh kwal-coh-sah pehr leh poon-too-reh dee zahn-zah-rah' },
    ],
  },
  {
    id: 'clothes',
    label: 'Clothes & tailor',
    icon: 'shirt',
    vocab: [
      { id: 'cthv1', english: 'T-shirt', italian: 'Maglietta', pronunciation: 'mah-yeh-tah' },
      { id: 'cthv2', english: 'Collared shirt', italian: 'Camicia', pronunciation: 'cah-mee-cha' },
      { id: 'cthv3', english: 'Sweatshirt', italian: 'Felpa', pronunciation: 'fel-pah' },
      { id: 'cthv4', english: 'Dress / suit', italian: 'Vestito', pronunciation: 'ves-tee-toh' },
      { id: 'cthv5', english: 'Skirt', italian: 'Gonna', pronunciation: 'go-nah' },
      { id: 'cthv6', english: 'Shoes', italian: 'Scarpe', pronunciation: 'scar-peh' },
      { id: 'cthv7', english: 'Pants', italian: 'Pantaloni', pronunciation: 'pahn-tah-loh-nee' },
      { id: 'cthv8', english: 'Jacket', italian: 'Giacca', pronunciation: 'jah-cah' },
      { id: 'cthv9', english: 'Coat', italian: 'Cappotto', pronunciation: 'cah-poh-toh' },
      { id: 'cthv10', english: 'Size', italian: 'Taglia', pronunciation: 'tah-yah' },
      { id: 'cthv11', english: 'Cotton', italian: 'Cotone', pronunciation: 'co-toh-neh' },
      { id: 'cthv12', english: 'Wool', italian: 'Lana', pronunciation: 'lah-nah' },
      { id: 'cthv13', english: 'Leather', italian: 'Pelle', pronunciation: 'peh-leh' },
    ],
    phrases: [
      { id: 'cth1', situation: 'Trying on', english: 'Can I try it on?', italian: 'Posso provarlo?', pronunciation: 'poh-so pro-var-lo' },
      { id: 'cth2', situation: 'Sizing', english: 'Do you have a bigger size?', italian: 'Avete una taglia più grande?', pronunciation: 'ah-veh-teh oo-nah tah-yah pyoo grahn-deh' },
      { id: 'cth3', situation: 'Fitting room', english: "Where's the fitting room?", italian: "Dov'è il camerino?", pronunciation: 'doh-veh eel cah-meh-ree-no' },
      { id: 'cth4', situation: 'Tailor', english: 'Can you shorten the pants?', italian: 'Si possono accorciare i pantaloni?', pronunciation: 'see poh-so-no ah-cor-chah-reh ee pahn-tah-loh-nee' },
      { id: 'cth5', situation: 'Sale', english: 'Is this on sale?', italian: 'Questo è in saldo?', pronunciation: 'kweh-stoh eh een sahl-doh' },
      { id: 'cth6', situation: 'Color', english: 'Do you have this in another color?', italian: 'Avete questo in un altro colore?', pronunciation: 'ah-veh-teh kweh-stoh een oon ahl-troh co-loh-reh' },
    ],
  },
  {
    id: 'beauty',
    label: 'Hair & beauty',
    icon: 'scissors',
    vocab: [
      { id: 'bev1', english: 'Hairdresser', italian: 'Parrucchiere', pronunciation: 'pah-roo-kyeh-reh' },
      { id: 'bev2', english: 'Barber', italian: 'Barbiere', pronunciation: 'bar-byeh-reh' },
      { id: 'bev3', english: 'Hair', italian: 'Capelli', pronunciation: 'cah-peh-lee' },
      { id: 'bev4', english: 'Beard', italian: 'Barba', pronunciation: 'bar-bah' },
      { id: 'bev5', english: 'Curly', italian: 'Ricci', pronunciation: 'ree-chee' },
      { id: 'bev6', english: 'Straight', italian: 'Lisci', pronunciation: 'lee-shee' },
      { id: 'bev7', english: 'Bangs / fringe', italian: 'Frangia', pronunciation: 'frahn-jah' },
      { id: 'bev8', english: 'Nail polish', italian: 'Smalto', pronunciation: 'smahl-toh' },
      { id: 'bev9', english: 'Massage', italian: 'Massaggio', pronunciation: 'mah-sah-joh' },
      { id: 'bev10', english: 'Wax (hair removal)', italian: 'Ceretta', pronunciation: 'cheh-reh-tah' },
      { id: 'bev11', english: 'Appointment', italian: 'Appuntamento', pronunciation: 'ah-poon-tah-men-toh' },
    ],
    phrases: [
      { id: 'be1', situation: 'Service', english: "I'd like a haircut", italian: 'Vorrei un taglio di capelli', pronunciation: 'voh-ray oon tah-yoh dee cah-peh-lee' },
      { id: 'be2', situation: 'Service', english: 'Just a trim', italian: 'Solo una spuntatina', pronunciation: 'soh-lo oo-nah spoon-tah-tee-nah' },
      { id: 'be3', situation: 'Availability', english: 'Do you have availability this morning?', italian: 'Avete posto stamattina?', pronunciation: 'ah-veh-teh poh-stoh stah-mah-tee-nah' },
      { id: 'be4', situation: 'Color', english: "I'd like to dye my hair", italian: 'Vorrei tingere i capelli', pronunciation: 'voh-ray teen-jeh-reh ee cah-peh-lee' },
      { id: 'be5', situation: 'Barber', english: 'Can you trim my beard?', italian: 'Può sistemarmi la barba?', pronunciation: 'pwoh see-steh-mar-mee lah bar-bah' },
      { id: 'be6', situation: 'Nails', english: 'How much is a manicure?', italian: 'Quanto costa la manicure?', pronunciation: 'kwahn-to co-stah lah mah-nee-koo-reh' },
    ],
  },
  {
    id: 'hygiene',
    label: 'Hygiene',
    icon: 'droplet',
    vocab: [
      { id: 'hyv1', english: 'Shower', italian: 'Doccia', pronunciation: 'doh-cha' },
      { id: 'hyv2', english: 'Soap', italian: 'Sapone', pronunciation: 'sah-poh-neh' },
      { id: 'hyv3', english: 'Shampoo', italian: 'Shampoo', pronunciation: 'sham-poh' },
      { id: 'hyv4', english: 'Conditioner', italian: 'Balsamo', pronunciation: 'bahl-sah-moh' },
      { id: 'hyv5', english: 'Perfume', italian: 'Profumo', pronunciation: 'pro-foo-moh' },
      { id: 'hyv6', english: 'Toothpaste', italian: 'Dentifricio', pronunciation: 'den-tee-free-choh' },
      { id: 'hyv7', english: 'Toothbrush', italian: 'Spazzolino', pronunciation: 'spah-tso-lee-no' },
      { id: 'hyv8', english: 'Razor', italian: 'Rasoio', pronunciation: 'rah-soh-yo' },
      { id: 'hyv9', english: 'Deodorant', italian: 'Deodorante', pronunciation: 'deh-oh-doh-rahn-teh' },
      { id: 'hyv10', english: 'Mouthwash', italian: 'Collutorio', pronunciation: 'cohl-loo-tohr-yoh' },
    ],
    phrases: [
      { id: 'hy1', situation: 'Finding items', english: 'Where do I find toothpaste?', italian: 'Dove trovo il dentifricio?', pronunciation: 'doh-veh troh-vo eel den-tee-free-choh' },
      { id: 'hy2', situation: 'Advice', english: 'Do you have shampoo for dry hair?', italian: 'Avete uno shampoo per capelli secchi?', pronunciation: 'ah-veh-teh oo-no sham-poh pehr cah-peh-lee seh-kee' },
      { id: 'hy3', situation: 'Preference', english: "I'm looking for an unscented deodorant", italian: 'Cerco un deodorante senza profumo', pronunciation: 'chehr-co oon deh-oh-doh-rahn-teh sen-tsah pro-foo-moh' },
      { id: 'hy4', situation: 'Sun', english: "I'd like sunscreen", italian: 'Vorrei una crema solare', pronunciation: 'voh-ray oo-nah creh-mah so-lah-reh' },
      { id: 'hy5', situation: 'Shaving', english: 'Do you have disposable razors?', italian: 'Avete rasoi usa e getta?', pronunciation: 'ah-veh-teh rah-soy oo-sah eh jeh-tah' },
      { id: 'hy6', situation: 'Skin', english: 'Is this soap gentle?', italian: 'Questo sapone è delicato?', pronunciation: 'kweh-stoh sah-poh-neh eh deh-lee-kah-toh' },
    ],
  },
  {
    id: 'jewelry',
    label: 'Jewelry',
    icon: 'diamond',
    vocab: [
      { id: 'jv1', english: 'Jewelry store', italian: 'Gioielleria', pronunciation: 'jo-yel-leh-ree-ya' },
      { id: 'jv2', english: 'Necklace', italian: 'Collana', pronunciation: 'coh-lah-nah' },
      { id: 'jv3', english: 'Bracelet', italian: 'Braccialetto', pronunciation: 'brah-cha-leh-toh' },
      { id: 'jv4', english: 'Ring', italian: 'Anello', pronunciation: 'ah-neh-loh' },
      { id: 'jv5', english: 'Earrings', italian: 'Orecchini', pronunciation: 'oh-reh-kee-nee' },
      { id: 'jv6', english: 'Watch', italian: 'Orologio', pronunciation: 'oh-roh-loh-joh' },
      { id: 'jv7', english: 'Gold', italian: 'Oro', pronunciation: 'oh-roh' },
      { id: 'jv8', english: 'Silver', italian: 'Argento', pronunciation: 'ar-jen-toh' },
      { id: 'jv9', english: 'Handbag', italian: 'Borsa', pronunciation: 'bohr-sah' },
      { id: 'jv10', english: 'Wallet', italian: 'Portafoglio', pronunciation: 'pohr-tah-foh-yoh' },
      { id: 'jv11', english: 'Scarf', italian: 'Sciarpa', pronunciation: 'shar-pah' },
    ],
    phrases: [
      { id: 'j1', situation: 'Browsing', english: "I'd like to see that necklace", italian: 'Vorrei vedere quella collana', pronunciation: 'voh-ray veh-deh-reh kweh-lah coh-lah-nah' },
      { id: 'j2', situation: 'Quality', english: 'Is it real gold?', italian: 'È oro vero?', pronunciation: 'eh oh-roh veh-roh' },
      { id: 'j3', situation: 'Choosing', english: 'Do you have silver earrings?', italian: "Avete orecchini d'argento?", pronunciation: 'ah-veh-teh oh-reh-kee-nee dar-jen-toh' },
      { id: 'j4', situation: 'Service', english: 'Can you engrave a name?', italian: 'Si può incidere un nome?', pronunciation: 'see pwoh een-chee-deh-reh oon noh-meh' },
      { id: 'j5', situation: 'Service', english: 'Do you do repairs?', italian: 'Fate riparazioni?', pronunciation: 'fah-teh ree-pah-rah-tsyoh-nee' },
      { id: 'j6', situation: 'Gift', english: 'Do you have gift wrapping?', italian: 'Avete una confezione regalo?', pronunciation: 'ah-veh-teh oo-nah con-feh-tsyoh-neh reh-gah-loh' },
    ],
  },
  {
    id: 'life',
    label: 'Life in Italy',
    icon: 'building',
    vocab: [
      { id: 'lv1', english: 'Show', italian: 'Spettacolo', pronunciation: 'speh-tah-coh-loh' },
      { id: 'lv2', english: 'Concert', italian: 'Concerto', pronunciation: 'cohn-chehr-toh' },
      { id: 'lv3', english: 'Tickets', italian: 'Biglietti', pronunciation: 'bee-yet-tee' },
      { id: 'lv4', english: 'Bills', italian: 'Bollette', pronunciation: 'boh-leh-teh' },
      { id: 'lv5', english: 'Utilities', italian: 'Utenze', pronunciation: 'oo-ten-tseh' },
      { id: 'lv6', english: 'Fine (penalty)', italian: 'Multa', pronunciation: 'mool-tah' },
      { id: 'lv7', english: 'Town square', italian: 'Piazza', pronunciation: 'pyah-tsah' },
      { id: 'lv8', english: 'Church', italian: 'Chiesa', pronunciation: 'kyeh-sah' },
      { id: 'lv9', english: 'Festival', italian: 'Sagra', pronunciation: 'sah-grah' },
      { id: 'lv10', english: 'Tobacco shop', italian: 'Tabaccaio', pronunciation: 'tah-bah-cah-yo', note: 'pay bills & buy transit tickets here' },
    ],
    phrases: [
      { id: 'l1', situation: 'Tickets', english: "I'd like two tickets for the show", italian: 'Vorrei due biglietti per lo spettacolo', pronunciation: 'voh-ray doo-eh bee-yet-tee pehr lo speh-tah-coh-loh' },
      { id: 'l2', situation: 'Bills', english: 'Where can I pay the bills?', italian: 'Dove posso pagare le bollette?', pronunciation: 'doh-veh poh-so pah-gah-reh leh boh-leh-teh' },
      { id: 'l3', situation: 'Opening hours', english: 'What time does the church open?', italian: 'A che ora apre la chiesa?', pronunciation: 'ah keh oh-rah ah-preh lah kyeh-sah' },
      { id: 'l4', situation: 'Events', english: 'Is there a festival this weekend?', italian: "C'è una sagra questo weekend?", pronunciation: 'cheh oo-nah sah-grah kweh-stoh weekend' },
      { id: 'l5', situation: 'Tabaccaio', english: 'Can I buy bus tickets at the tabaccaio?', italian: 'Posso comprare i biglietti del bus dal tabaccaio?', pronunciation: 'poh-so com-prah-reh ee bee-yet-tee del boos dahl tah-bah-cah-yo' },
      { id: 'l6', situation: 'Fines', english: 'I got a parking fine', italian: 'Ho preso una multa', pronunciation: 'oh preh-so oo-nah mool-tah' },
    ],
  },
  {
    id: 'transport',
    label: 'Transport',
    icon: 'bus',
    vocab: [
      { id: 'tv1', english: 'Train', italian: 'Treno', pronunciation: 'treh-noh' },
      { id: 'tv2', english: 'Metro', italian: 'Metro', pronunciation: 'met-roh' },
      { id: 'tv3', english: 'Funicular', italian: 'Funicolare', pronunciation: 'foo-nee-coh-lah-reh' },
      { id: 'tv4', english: 'Bus', italian: 'Pullman', pronunciation: 'pool-mahn' },
      { id: 'tv5', english: 'Station', italian: 'Stazione', pronunciation: 'stah-tsyoh-neh' },
      { id: 'tv6', english: 'Ticket', italian: 'Biglietto', pronunciation: 'bee-yet-toh' },
      { id: 'tv7', english: 'Stop', italian: 'Fermata', pronunciation: 'fehr-mah-tah' },
      { id: 'tv8', english: 'Platform', italian: 'Binario', pronunciation: 'bee-nah-ryoh' },
      { id: 'tv9', english: 'Ferry', italian: 'Traghetto', pronunciation: 'trah-geh-toh' },
      { id: 'tv10', english: 'Hydrofoil', italian: 'Aliscafo', pronunciation: 'ah-lee-scah-fo' },
      { id: 'tv11', english: 'Parking', italian: 'Parcheggio', pronunciation: 'par-keh-joh', note: 'blue = paid, white = free, yellow = restricted' },
    ],
    phrases: [
      { id: 't1', situation: 'Tickets', english: 'A ticket to Naples, please', italian: 'Un biglietto per Napoli, per favore', pronunciation: 'oon bee-yet-toh pehr nah-po-lee pehr fah-voh-reh' },
      { id: 't2', situation: 'Schedule', english: 'What time does the next train leave?', italian: 'A che ora parte il prossimo treno?', pronunciation: 'ah keh oh-rah par-teh eel proh-see-mo treh-noh' },
      { id: 't3', situation: 'Platform', english: 'Which platform does it leave from?', italian: 'Da quale binario parte?', pronunciation: 'dah kwah-leh bee-nah-ryoh par-teh' },
      { id: 't4', situation: 'Directions', english: 'Does this bus go downtown?', italian: 'Questo autobus va in centro?', pronunciation: 'kweh-stoh ow-toh-boos vah een chen-troh' },
      { id: 't5', situation: 'Fare', english: 'How much is the fare to the airport?', italian: "Quanto costa la corsa fino all'aeroporto?", pronunciation: 'kwahn-to co-stah lah cor-sah fee-no ah-lah-eh-ro-por-toh' },
      { id: 't6', situation: 'Ferry', english: 'Ferry to Capri / Ischia / Procida', italian: 'Traghetto per Capri / Ischia / Procida', pronunciation: 'trah-geh-toh pehr kah-pree / ee-skyah / pro-chee-dah' },
    ],
  },
  {
    id: 'emergency',
    label: 'Emergency',
    icon: 'alert-triangle',
    vocab: [
      { id: 'ev1', english: 'Help', italian: 'Aiuto', pronunciation: 'ah-yoo-to' },
      { id: 'ev2', english: 'Police', italian: 'Polizia', pronunciation: 'po-leet-zee-ah' },
      { id: 'ev3', english: 'Military police', italian: 'Carabinieri', pronunciation: 'cah-rah-bee-nyeh-ree' },
      { id: 'ev4', english: 'Ambulance', italian: 'Ambulanza', pronunciation: 'am-boo-lahn-zah' },
      { id: 'ev5', english: 'Hospital', italian: 'Ospedale', pronunciation: 'os-peh-dah-leh' },
      { id: 'ev6', english: 'Doctor', italian: 'Medico', pronunciation: 'meh-dee-co' },
      { id: 'ev7', english: 'Firefighters', italian: 'Pompieri', pronunciation: 'pom-pyeh-ree' },
      { id: 'ev8', english: 'Thief', italian: 'Ladro', pronunciation: 'lah-droh' },
      { id: 'ev9', english: 'Passport', italian: 'Passaporto', pronunciation: 'pas-sah-por-to' },
      { id: 'ev10', english: 'Embassy', italian: 'Ambasciata', pronunciation: 'am-bah-shah-tah' },
    ],
    phrases: [
      { id: 'e1', situation: 'Urgent', english: "Help, it's an emergency!", italian: "Aiuto, è un'emergenza!", pronunciation: 'ah-yoo-to eh oon eh-mehr-jen-tsah' },
      { id: 'e2', situation: 'Medical', english: 'Call an ambulance!', italian: "Chiamate un'ambulanza!", pronunciation: 'kyah-mah-teh oon am-boo-lahn-zah' },
      { id: 'e3', situation: 'Medical', english: 'I need a doctor', italian: 'Ho bisogno di un medico', pronunciation: 'oh bee-zon-yo dee oon meh-dee-co' },
      { id: 'e4', situation: 'Theft', english: 'They stole my wallet', italian: 'Mi hanno rubato il portafoglio', pronunciation: 'mee ahn-no roo-bah-toh eel pohr-tah-foh-yoh' },
      { id: 'e5', situation: 'Hospital', english: "Where's the nearest emergency room?", italian: "Dov'è il pronto soccorso più vicino?", pronunciation: 'doh-veh eel pron-toh soh-cor-so pyoo vee-chee-no' },
      { id: 'e6', situation: 'Lost', english: 'I lost my passport', italian: 'Ho perso il passaporto', pronunciation: 'oh pehr-so eel pas-sah-por-to' },
      { id: 'e7', situation: 'Police', english: 'Call the police!', italian: 'Chiamate la polizia!', pronunciation: 'kyah-mah-teh lah po-leet-zee-ah' },
    ],
  },
  {
    id: 'neapolitan',
    label: 'Neapolitan',
    icon: 'map-pin',
    vocab: [
      { id: 'napv1', english: 'Hey / hi (informal)', italian: 'Ciao', pronunciation: 'weh', neapolitan: 'Uè' },
      { id: 'napv2', english: 'Boy / dude', italian: 'Ragazzo', pronunciation: 'gwah-lyoh-neh', neapolitan: 'Guaglione' },
      { id: 'napv3', english: 'Girl', italian: 'Ragazza', pronunciation: 'gwah-lyoh-nah', neapolitan: 'Guagliona' },
      { id: 'napv4', english: 'Now', italian: 'Adesso', pronunciation: 'moh', neapolitan: "Mo'" },
      { id: 'napv5', english: 'A lot / very', italian: 'Molto', pronunciation: 'ah-sah-yeh', neapolitan: 'Assaje' },
      { id: 'napv6', english: 'Money', italian: 'I soldi', pronunciation: 'eh sord', neapolitan: "'E sord'" },
      { id: 'napv7', english: 'Buddy / mate', italian: 'Amico', pronunciation: 'koom-pah', neapolitan: 'Cumpà' },
      { id: 'napv8', english: 'Beautiful / great', italian: 'Bello', pronunciation: 'bell', neapolitan: "Bell'" },
      { id: 'napv9', english: 'The bill', italian: 'Il conto', pronunciation: 'o koon-to', neapolitan: "'O cunto" },
      { id: 'napv10', english: 'To eat / food', italian: 'Il mangiare', pronunciation: 'o mah-nyah', neapolitan: "'O magnà" },
    ],
    phrases: [
      { id: 'nap1', situation: 'Greeting', english: 'Have a good day!', italian: 'Buona giornata!', pronunciation: 'boh-nah yoor-nah-tah', neapolitan: 'Bona jurnata!' },
      { id: 'nap2', situation: 'Small talk', english: 'How are you?', italian: 'Come stai?', pronunciation: 'kom-meh stah-yeh', neapolitan: 'Comme staje?' },
      { id: 'nap3', situation: 'Small talk', english: 'All good?', italian: 'Tutto a posto?', pronunciation: 'toot ah post', neapolitan: "Tutt' a post'?" },
      { id: 'nap4', situation: 'Encouragement', english: "Let's go! / Come on!", italian: 'Andiamo!', pronunciation: 'yahm-mo bell', neapolitan: "Jammo bell'!" },
      { id: 'nap5', situation: 'Admiration', english: 'How beautiful!', italian: 'Che bello!', pronunciation: 'keh bell', neapolitan: "Che bell'!" },
      { id: 'nap6', situation: 'Reassurance', english: "Never mind / it's nothing", italian: 'Non fa niente', pronunciation: 'noon fah nyen-teh', neapolitan: 'Nun fa niente' },
      { id: 'nap7', situation: 'At the table', english: 'Enjoy your meal!', italian: 'Buon appetito!', pronunciation: 'bboh-nah mah-nyah-tah', neapolitan: 'Bbona magnata!' },
    ],
  },
];
