// AUTO-GENERATED by scripts/geocode-stations.mjs — real OSM coordinates.
// Re-run that script to refresh. Do not hand-edit coordinates from memory.

export type Station = { name: string; lat: number; lng: number };
export type TransitMapLine = {
  id: string;
  label: string;
  color: string;
  stations?: Station[];
  segments?: Station[][];
};

export const transitMapLines: TransitMapLine[] = [
  {
    "id": "l1",
    "label": "Metro Line 1",
    "color": "#E0A100",
    "stations": [
      {
        "name": "Piscinola",
        "lat": 40.86986,
        "lng": 14.21915
      },
      {
        "name": "Chiaiano",
        "lat": 40.89238,
        "lng": 14.2409
      },
      {
        "name": "Frullone",
        "lat": 40.88026,
        "lng": 14.23123
      },
      {
        "name": "Colli Aminei",
        "lat": 40.86848,
        "lng": 14.22733
      },
      {
        "name": "Policlinico",
        "lat": 40.8652,
        "lng": 14.22151
      },
      {
        "name": "Rione Alto",
        "lat": 40.85431,
        "lng": 14.21887
      },
      {
        "name": "Montedonzelli",
        "lat": 40.85461,
        "lng": 14.22691
      },
      {
        "name": "Medaglie d'Oro",
        "lat": 40.85056,
        "lng": 14.23081
      },
      {
        "name": "Vanvitelli",
        "lat": 40.84392,
        "lng": 14.23175
      },
      {
        "name": "Quattro Giornate",
        "lat": 40.84634,
        "lng": 14.22512
      },
      {
        "name": "Salvator Rosa",
        "lat": 40.85132,
        "lng": 14.23696
      },
      {
        "name": "Materdei",
        "lat": 40.85473,
        "lng": 14.24582
      },
      {
        "name": "Museo",
        "lat": 40.85361,
        "lng": 14.25115
      },
      {
        "name": "Dante",
        "lat": 40.84987,
        "lng": 14.24968
      },
      {
        "name": "Toledo",
        "lat": 40.84244,
        "lng": 14.2488
      },
      {
        "name": "Municipio",
        "lat": 40.83933,
        "lng": 14.25286
      },
      {
        "name": "Università",
        "lat": 40.84553,
        "lng": 14.25511
      },
      {
        "name": "Duomo",
        "lat": 40.84778,
        "lng": 14.26164
      },
      {
        "name": "Garibaldi",
        "lat": 40.85259,
        "lng": 14.27237
      }
    ]
  },
  {
    "id": "l2",
    "label": "Metro Line 2",
    "color": "#2E6FB7",
    "stations": [
      {
        "name": "Gianturco",
        "lat": 40.8459,
        "lng": 14.28723
      },
      {
        "name": "Piazza Garibaldi",
        "lat": 40.85338,
        "lng": 14.27113
      },
      {
        "name": "Piazza Cavour",
        "lat": 40.85467,
        "lng": 14.2535
      },
      {
        "name": "Montesanto",
        "lat": 40.84685,
        "lng": 14.24462
      },
      {
        "name": "Piazza Amedeo",
        "lat": 40.8376,
        "lng": 14.23351
      },
      {
        "name": "Mergellina",
        "lat": 40.83144,
        "lng": 14.21919
      },
      {
        "name": "Campi Flegrei",
        "lat": 40.82218,
        "lng": 14.19464
      },
      {
        "name": "Bagnoli",
        "lat": 40.81934,
        "lng": 14.16669
      },
      {
        "name": "Pozzuoli",
        "lat": 40.82899,
        "lng": 14.1177
      }
    ]
  },
  {
    "id": "l6",
    "label": "Metro Line 6",
    "color": "#C84E8F",
    "stations": [
      {
        "name": "Mostra",
        "lat": 40.82434,
        "lng": 14.19366
      },
      {
        "name": "Mergellina",
        "lat": 40.83144,
        "lng": 14.21919
      },
      {
        "name": "Arco Mirelli",
        "lat": 40.83254,
        "lng": 14.22669
      },
      {
        "name": "San Pasquale",
        "lat": 40.83364,
        "lng": 14.2347
      },
      {
        "name": "Chiaia",
        "lat": 40.83559,
        "lng": 14.23876
      },
      {
        "name": "Municipio",
        "lat": 40.83933,
        "lng": 14.25286
      }
    ]
  },
  {
    "id": "fun",
    "label": "Funiculars",
    "color": "#DE7C2B",
    "segments": [
      [
        {
          "name": "Centrale",
          "lat": 40.83894,
          "lng": 14.24769
        },
        {
          "name": "Centrale (top)",
          "lat": 40.84262,
          "lng": 14.23338
        }
      ],
      [
        {
          "name": "Chiaia",
          "lat": 40.83812,
          "lng": 14.2347
        },
        {
          "name": "Chiaia (top)",
          "lat": 40.84272,
          "lng": 14.23252
        }
      ],
      [
        {
          "name": "Montesanto",
          "lat": 40.84685,
          "lng": 14.24462
        },
        {
          "name": "Montesanto (top)",
          "lat": 40.84378,
          "lng": 14.23487
        }
      ],
      [
        {
          "name": "Mergellina",
          "lat": 40.82748,
          "lng": 14.22009
        },
        {
          "name": "Mergellina (top)",
          "lat": 40.81698,
          "lng": 14.20122
        }
      ]
    ]
  }
];
